const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');let time=0;
class Clock extends Date{constructor(){super(time);}}
function load(name,cb){const c={Math,Date:Clock,isFinite,inlet:0,error:()=>{},arrayfromargs:a=>Array.from(a),Task:function(){this.cancel=()=>{};this.repeat=()=>{};},outlet:cb||(()=>{})};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,name),'utf8'),c);return c;}
let flat=0,models=0;const gen=load('cnmat_sinusoid_model_generator_v16.js',(out)=>{if(out===4)models++;});const shapes=load('dynamic_shape_library_v16.js');let engine;
engine=load('multislider_interpolation_engine_v16.js',(out,msg)=>{if(out===3){gen.inlet=7;gen[msg]();}else if(out===4){assert.equal(msg,'flatmenus');shapes.flatmenus();flat++;}else if(msg!=='size'){gen.inlet=out;gen.list(...msg);}});
engine.inlet=9;engine.msg_int(256);gen.inlet=3;gen.msg_int(256);
for(let ch=0;ch<3;ch++){engine.inlet=ch+3;engine.list(...Array.from({length:256},(_,i)=>ch===1?i/255:.8));}
engine.inlet=9;engine.msg_int(30);const untouched=JSON.stringify(engine.memory[2]);models=0;engine.inlet=10;engine.PartialAmplitudes_to_Inharmonicity();assert.equal(models,1);assert.equal(JSON.stringify(engine.memory[0]),JSON.stringify(engine.memory[1]));assert.equal(JSON.stringify(engine.memory[2]),untouched);assert.notEqual(engine.memory[0],engine.memory[1]);
models=0;engine.PartialAmplitudes_to_HarmonicAnchor();assert.equal(models,1);assert.equal(JSON.stringify(engine.memory[2]),JSON.stringify(engine.memory[1]));
shapes.inharmonicityShape=10;shapes.amplitudeShape=12;shapes.harmonicShape=17;engine.alloff();assert(engine.memory.every(a=>a.every(x=>x===0)));assert.equal(flat,1);assert.equal(shapes.inharmonicityShape,-1);assert.equal(shapes.amplitudeShape,-1);assert.equal(shapes.harmonicShape,-1);assert.equal(engine.componentCount,30);
let layers=[],events=0;const stops=load('ec_sinusoid_synth_stops_v16.js',(out,v)=>{if(out===0){layers=Array.from(v);events++;engine.inlet=10;engine.stoplayers(...layers.slice(1));}});assert.equal(events,0);stops.loadbang();assert.equal(events,0);
stops.tail(1);models=0;stops.registration('CornetV');assert.equal(models,1);assert.equal(layers.length,769);assert.equal(layers[0],'stoplayers');for(let i=0;i<256;i++)assert.equal(engine.memory[1][i]>0,i<5);assert(engine.memory[0].every(x=>x===0));assert(engine.memory[2].every(x=>x===0));assert(Math.abs(engine.memory[1].reduce((a,b)=>a+b,0)-.8)<3e-6);
stops.tail(24);stops.registration('StoppedFlute');for(let i=0;i<256;i++)if((i+1)%2===0)assert.equal(engine.memory[1][i],0);
stops.registration('SharpMixture');assert(engine.memory[1][3]>0&&engine.memory[1][5]>0&&engine.memory[1][7]>0);assert(engine.memory[1].slice(0,3).every(x=>x===0));
stops.inlet=1;stops.msg_float(27.5);stops.inlet=2;stops.msg_float(.5);gen.inlet=4;gen.msg_float(27.5);gen.inlet=5;gen.msg_float(.5);stops.beathz(.2);stops.registration('CelesteII');assert.equal(JSON.stringify(engine.memory[1]),JSON.stringify(engine.memory[2]));assert.equal(engine.memory[0][0],0);assert(engine.memory[0][1]>0);assert(Math.abs(engine.memory[0][1]*.5*gen.erbBandwidth(55)-.2)<.00002);
const primary=JSON.stringify(engine.memory[1]);stops.stop(0,1);assert.equal(JSON.stringify(engine.memory[1]),primary);stops.apply();assert.notEqual(JSON.stringify(engine.memory[1]),primary);
stops.clear();assert(engine.memory.every(a=>a.every(x=>x===0)));assert(stops.selected.every(x=>x===false));
const before=JSON.stringify(engine.memory);engine.inlet=10;engine.stoplayers(1,2,3);assert.equal(JSON.stringify(engine.memory),before);
function graph(p){const ids=new Map(p.boxes.map(x=>[x.box.id,x.box]));assert.equal(ids.size,p.boxes.length);for(const {patchline:l} of p.lines){assert(ids.has(l.source[0])&&ids.has(l.destination[0]));assert(l.source[1]<ids.get(l.source[0]).numoutlets);assert(l.destination[1]<ids.get(l.destination[0]).numinlets);}for(const {box:b} of p.boxes){if(b.patcher)graph(b.patcher);if(b.text?.startsWith('js '))assert(fs.existsSync(path.join(__dirname,b.text.slice(3))));}}
for(const file of ['_ec_sinusoids_synth_stage_v16.maxpat','ec_sinusoid_synth_stops_v16.maxpat','ec_sinusoid_synth_stops_research_v16.maxpat'])graph(JSON.parse(fs.readFileSync(path.join(__dirname,file))).patcher);
const p=JSON.parse(fs.readFileSync(path.join(__dirname,'_ec_sinusoids_synth_stage_v16.maxpat'))).patcher;
const menus=['syn-freq-shape-menu','syn-amp-shape-menu','syn-harmonic-shape-menu'];for(const id of menus)assert(p.lines.some(x=>x.patchline.source[0]==='flat-menus14'&&x.patchline.destination[0]===id));
assert(p.lines.some(x=>x.patchline.source[0]==='obj-28'&&x.patchline.destination[0]==='syn-interpolation-js'&&x.patchline.destination[1]===10));
console.log('PASS: both full-bank named copies, single model transactions, alloff zero banks + silent shape/menu reset, rank algebra/Cornet/mutations/odd spectra, independent proposed selections, exact-anchor beating, 256-slot apply, clear, malformed input rejection, all patch graphs/dependencies.');
